# Generated by Django 5.1.3 on 2025-01-08 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_country', to='KYBAPI.country')),
            ],
        ),
        migrations.CreateModel(
            name='Clicks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fare', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('distance', models.CharField(max_length=10)),
                ('finaldestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='final_destination_click', to='KYBAPI.destination')),
                ('startdestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='start_destination_click', to='KYBAPI.destination')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.CharField(max_length=10)),
                ('reaching_time', models.CharField(max_length=10)),
                ('fare', models.CharField(max_length=20)),
                ('confirmed', models.BooleanField()),
                ('distance', models.CharField(max_length=20)),
                ('finaldestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finaldestinations', to='KYBAPI.destination')),
                ('startdestination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='startdestinations', to='KYBAPI.destination')),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state', to='KYBAPI.country')),
            ],
        ),
        migrations.AddField(
            model_name='destination',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_state', to='KYBAPI.state'),
        ),
        migrations.CreateModel(
            name='SubDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance', models.IntegerField()),
                ('time', models.CharField(max_length=50)),
                ('SNO', models.IntegerField()),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sub_Destination', to='KYBAPI.bus')),
                ('destinationName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KYBAPI.destination')),
            ],
        ),
    ]
