# Generated by Django 5.1.3 on 2025-01-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYBAPI', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bus',
            name='booking_link',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='online_avilable',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bus',
            name='start_google_link',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AddField(
            model_name='destination',
            name='google_link',
            field=models.CharField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
