# Generated by Django 5.1.3 on 2025-01-08 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYBAPI', '0002_bus_booking_link_bus_company_bus_online_avilable_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bus_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='start_google_link',
            new_name='start_map_link',
        ),
        migrations.AlterField(
            model_name='bus',
            name='distance',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='fare',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='finaldestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='finaldestinations', to='KYBAPI.destination'),
        ),
        migrations.AlterField(
            model_name='bus',
            name='reaching_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='start_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='startdestination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='startdestinations', to='KYBAPI.destination'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_country', to='KYBAPI.country'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='destination',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination_state', to='KYBAPI.state'),
        ),
        migrations.AddField(
            model_name='bus',
            name='bus_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bus_service', to='KYBAPI.bus_service'),
        ),
    ]
