# Generated by Django 5.1.3 on 2025-03-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KYBAPI', '0004_rename_fare_bus_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='up_loc_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
